// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: detail.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Atakmap.Commoncommo.Protobuf.V1 {

  /// <summary>Holder for reflection information generated from detail.proto</summary>
  public static partial class DetailReflection {

    #region Descriptor
    /// <summary>File descriptor for detail.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DetailReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxkZXRhaWwucHJvdG8SH2F0YWttYXAuY29tbW9uY29tbW8ucHJvdG9idWYu",
            "djEaDWNvbnRhY3QucHJvdG8aC2dyb3VwLnByb3RvGhdwcmVjaXNpb25sb2Nh",
            "dGlvbi5wcm90bxoMc3RhdHVzLnByb3RvGgp0YWt2LnByb3RvGgt0cmFjay5w",
            "cm90byKBAwoGRGV0YWlsEhEKCXhtbERldGFpbBgBIAEoCRI5Cgdjb250YWN0",
            "GAIgASgLMiguYXRha21hcC5jb21tb25jb21tby5wcm90b2J1Zi52MS5Db250",
            "YWN0EjUKBWdyb3VwGAMgASgLMiYuYXRha21hcC5jb21tb25jb21tby5wcm90",
            "b2J1Zi52MS5Hcm91cBJNChFwcmVjaXNpb25Mb2NhdGlvbhgEIAEoCzIyLmF0",
            "YWttYXAuY29tbW9uY29tbW8ucHJvdG9idWYudjEuUHJlY2lzaW9uTG9jYXRp",
            "b24SNwoGc3RhdHVzGAUgASgLMicuYXRha21hcC5jb21tb25jb21tby5wcm90",
            "b2J1Zi52MS5TdGF0dXMSMwoEdGFrdhgGIAEoCzIlLmF0YWttYXAuY29tbW9u",
            "Y29tbW8ucHJvdG9idWYudjEuVGFrdhI1CgV0cmFjaxgHIAEoCzImLmF0YWtt",
            "YXAuY29tbW9uY29tbW8ucHJvdG9idWYudjEuVHJhY2tCAkgDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Atakmap.Commoncommo.Protobuf.V1.ContactReflection.Descriptor, global::Atakmap.Commoncommo.Protobuf.V1.GroupReflection.Descriptor, global::Atakmap.Commoncommo.Protobuf.V1.PrecisionlocationReflection.Descriptor, global::Atakmap.Commoncommo.Protobuf.V1.StatusReflection.Descriptor, global::Atakmap.Commoncommo.Protobuf.V1.TakvReflection.Descriptor, global::Atakmap.Commoncommo.Protobuf.V1.TrackReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Atakmap.Commoncommo.Protobuf.V1.Detail), global::Atakmap.Commoncommo.Protobuf.V1.Detail.Parser, new[]{ "XmlDetail", "Contact", "Group", "PrecisionLocation", "Status", "Takv", "Track" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Detail : pb::IMessage<Detail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Detail> _parser = new pb::MessageParser<Detail>(() => new Detail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Detail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Atakmap.Commoncommo.Protobuf.V1.DetailReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Detail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Detail(Detail other) : this() {
      xmlDetail_ = other.xmlDetail_;
      contact_ = other.contact_ != null ? other.contact_.Clone() : null;
      group_ = other.group_ != null ? other.group_.Clone() : null;
      precisionLocation_ = other.precisionLocation_ != null ? other.precisionLocation_.Clone() : null;
      status_ = other.status_ != null ? other.status_.Clone() : null;
      takv_ = other.takv_ != null ? other.takv_.Clone() : null;
      track_ = other.track_ != null ? other.track_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Detail Clone() {
      return new Detail(this);
    }

    /// <summary>Field number for the "xmlDetail" field.</summary>
    public const int XmlDetailFieldNumber = 1;
    private string xmlDetail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string XmlDetail {
      get { return xmlDetail_; }
      set {
        xmlDetail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contact" field.</summary>
    public const int ContactFieldNumber = 2;
    private global::Atakmap.Commoncommo.Protobuf.V1.Contact contact_;
    /// <summary>
    /// &lt;contact>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atakmap.Commoncommo.Protobuf.V1.Contact Contact {
      get { return contact_; }
      set {
        contact_ = value;
      }
    }

    /// <summary>Field number for the "group" field.</summary>
    public const int GroupFieldNumber = 3;
    private global::Atakmap.Commoncommo.Protobuf.V1.Group group_;
    /// <summary>
    /// &lt;__group>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atakmap.Commoncommo.Protobuf.V1.Group Group {
      get { return group_; }
      set {
        group_ = value;
      }
    }

    /// <summary>Field number for the "precisionLocation" field.</summary>
    public const int PrecisionLocationFieldNumber = 4;
    private global::Atakmap.Commoncommo.Protobuf.V1.PrecisionLocation precisionLocation_;
    /// <summary>
    /// &lt;precisionlocation>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atakmap.Commoncommo.Protobuf.V1.PrecisionLocation PrecisionLocation {
      get { return precisionLocation_; }
      set {
        precisionLocation_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 5;
    private global::Atakmap.Commoncommo.Protobuf.V1.Status status_;
    /// <summary>
    /// &lt;status>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atakmap.Commoncommo.Protobuf.V1.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "takv" field.</summary>
    public const int TakvFieldNumber = 6;
    private global::Atakmap.Commoncommo.Protobuf.V1.Takv takv_;
    /// <summary>
    /// &lt;takv>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atakmap.Commoncommo.Protobuf.V1.Takv Takv {
      get { return takv_; }
      set {
        takv_ = value;
      }
    }

    /// <summary>Field number for the "track" field.</summary>
    public const int TrackFieldNumber = 7;
    private global::Atakmap.Commoncommo.Protobuf.V1.Track track_;
    /// <summary>
    /// &lt;track>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atakmap.Commoncommo.Protobuf.V1.Track Track {
      get { return track_; }
      set {
        track_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Detail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Detail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (XmlDetail != other.XmlDetail) return false;
      if (!object.Equals(Contact, other.Contact)) return false;
      if (!object.Equals(Group, other.Group)) return false;
      if (!object.Equals(PrecisionLocation, other.PrecisionLocation)) return false;
      if (!object.Equals(Status, other.Status)) return false;
      if (!object.Equals(Takv, other.Takv)) return false;
      if (!object.Equals(Track, other.Track)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (XmlDetail.Length != 0) hash ^= XmlDetail.GetHashCode();
      if (contact_ != null) hash ^= Contact.GetHashCode();
      if (group_ != null) hash ^= Group.GetHashCode();
      if (precisionLocation_ != null) hash ^= PrecisionLocation.GetHashCode();
      if (status_ != null) hash ^= Status.GetHashCode();
      if (takv_ != null) hash ^= Takv.GetHashCode();
      if (track_ != null) hash ^= Track.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (XmlDetail.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(XmlDetail);
      }
      if (contact_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Contact);
      }
      if (group_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Group);
      }
      if (precisionLocation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PrecisionLocation);
      }
      if (status_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Status);
      }
      if (takv_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Takv);
      }
      if (track_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Track);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (XmlDetail.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(XmlDetail);
      }
      if (contact_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Contact);
      }
      if (group_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Group);
      }
      if (precisionLocation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PrecisionLocation);
      }
      if (status_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Status);
      }
      if (takv_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Takv);
      }
      if (track_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Track);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (XmlDetail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(XmlDetail);
      }
      if (contact_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Contact);
      }
      if (group_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Group);
      }
      if (precisionLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrecisionLocation);
      }
      if (status_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (takv_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Takv);
      }
      if (track_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Track);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Detail other) {
      if (other == null) {
        return;
      }
      if (other.XmlDetail.Length != 0) {
        XmlDetail = other.XmlDetail;
      }
      if (other.contact_ != null) {
        if (contact_ == null) {
          Contact = new global::Atakmap.Commoncommo.Protobuf.V1.Contact();
        }
        Contact.MergeFrom(other.Contact);
      }
      if (other.group_ != null) {
        if (group_ == null) {
          Group = new global::Atakmap.Commoncommo.Protobuf.V1.Group();
        }
        Group.MergeFrom(other.Group);
      }
      if (other.precisionLocation_ != null) {
        if (precisionLocation_ == null) {
          PrecisionLocation = new global::Atakmap.Commoncommo.Protobuf.V1.PrecisionLocation();
        }
        PrecisionLocation.MergeFrom(other.PrecisionLocation);
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Atakmap.Commoncommo.Protobuf.V1.Status();
        }
        Status.MergeFrom(other.Status);
      }
      if (other.takv_ != null) {
        if (takv_ == null) {
          Takv = new global::Atakmap.Commoncommo.Protobuf.V1.Takv();
        }
        Takv.MergeFrom(other.Takv);
      }
      if (other.track_ != null) {
        if (track_ == null) {
          Track = new global::Atakmap.Commoncommo.Protobuf.V1.Track();
        }
        Track.MergeFrom(other.Track);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            XmlDetail = input.ReadString();
            break;
          }
          case 18: {
            if (contact_ == null) {
              Contact = new global::Atakmap.Commoncommo.Protobuf.V1.Contact();
            }
            input.ReadMessage(Contact);
            break;
          }
          case 26: {
            if (group_ == null) {
              Group = new global::Atakmap.Commoncommo.Protobuf.V1.Group();
            }
            input.ReadMessage(Group);
            break;
          }
          case 34: {
            if (precisionLocation_ == null) {
              PrecisionLocation = new global::Atakmap.Commoncommo.Protobuf.V1.PrecisionLocation();
            }
            input.ReadMessage(PrecisionLocation);
            break;
          }
          case 42: {
            if (status_ == null) {
              Status = new global::Atakmap.Commoncommo.Protobuf.V1.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 50: {
            if (takv_ == null) {
              Takv = new global::Atakmap.Commoncommo.Protobuf.V1.Takv();
            }
            input.ReadMessage(Takv);
            break;
          }
          case 58: {
            if (track_ == null) {
              Track = new global::Atakmap.Commoncommo.Protobuf.V1.Track();
            }
            input.ReadMessage(Track);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            XmlDetail = input.ReadString();
            break;
          }
          case 18: {
            if (contact_ == null) {
              Contact = new global::Atakmap.Commoncommo.Protobuf.V1.Contact();
            }
            input.ReadMessage(Contact);
            break;
          }
          case 26: {
            if (group_ == null) {
              Group = new global::Atakmap.Commoncommo.Protobuf.V1.Group();
            }
            input.ReadMessage(Group);
            break;
          }
          case 34: {
            if (precisionLocation_ == null) {
              PrecisionLocation = new global::Atakmap.Commoncommo.Protobuf.V1.PrecisionLocation();
            }
            input.ReadMessage(PrecisionLocation);
            break;
          }
          case 42: {
            if (status_ == null) {
              Status = new global::Atakmap.Commoncommo.Protobuf.V1.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 50: {
            if (takv_ == null) {
              Takv = new global::Atakmap.Commoncommo.Protobuf.V1.Takv();
            }
            input.ReadMessage(Takv);
            break;
          }
          case 58: {
            if (track_ == null) {
              Track = new global::Atakmap.Commoncommo.Protobuf.V1.Track();
            }
            input.ReadMessage(Track);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
